"""add wallet_challenges for signed ownership proof

Revision ID: cab0eea8fd85
Revises: b48cbc369e9f
Create Date: 2026-08-01 01:58:52.026160+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cab0eea8fd85'
down_revision: Union[str, None] = 'b48cbc369e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_challenges',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=132), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_challenges_nonce'), 'wallet_challenges', ['nonce'], unique=True)
    op.create_index(op.f('ix_wallet_challenges_user_id'), 'wallet_challenges', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_challenges_user_id'), table_name='wallet_challenges')
    op.drop_index(op.f('ix_wallet_challenges_nonce'), table_name='wallet_challenges')
    op.drop_table('wallet_challenges')
    # ### end Alembic commands ###
